apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  # Requirement: Using NodePort to make the app accessible on your local machine
  type: NodePort
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # You can access the app at http://localhost:30001
      nodePort: 30001